# Adding and Subtracting Matrices

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])

In [3]:
print(np.add(x, y))

[[ 5  7]
 [ 9 11]]


In [4]:
x + y

array([[ 5,  7],
       [ 9, 11]])

In [5]:
print(np.subtract(x, y))

[[-3 -3]
 [-3 -3]]
