Axis

In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,0,1]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [4]:
x.sum(axis=0)

array([12,  7, 10])

In [5]:
x.sum(axis=1)

array([ 6, 15,  8])