Axis

In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,0,1]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [4]:
x.sum(axis=0)   # sum of column

array([12,  7, 10])

In [5]:
x.sum(axis=1)  # sum of row

array([ 6, 15,  8])

In [6]:
x.T    #transpose of array

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [8]:
x.ndim

2

In [9]:
x.size

9

In [10]:
x.nbytes

72

In [17]:
x.argmax(axis=0)

array([2, 1, 1])

In [18]:
x.argmin(axis=1)

array([0, 0, 1])

In [19]:
x.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [20]:
np.where(x>5)

(array([1, 2]), array([2, 0]))

In [21]:
np.count_nonzero(x)

8

In [22]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 2]))

In [ ]:
x[1,2] = 0

In [13]:
x1 = np.array([1,2,3,6,0])
x1.argmax()

3

In [14]:
x1.argmin()

4

In [16]:
x1.argsort()

array([0, 1, 2, 3, 4])