# Welcome to `numpy`

# Create basic array

In [1]:
# create an array
import numpy as np
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [2]:
# create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# Create empty array with two element
np.empty(2)

array([2.05833592e-312, 2.33419537e-312])

In [5]:
# create an array with range of element
np.arange(4)

array([0, 1, 2, 3])

In [7]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.ones(2, dtype=np.int32)

array([1, 1], dtype=int32)

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Printing 1d, 2d, 3d array

# 1D Array

In [19]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


# 2D Array

In [24]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 3D Array

In [29]:
b = np.arange(12).reshape(3,1,4)
print(b)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [30]:
c = np.arange(24).reshape(3, 2, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
