# Create basic array

In [1]:
# create an array
import numpy as np
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [2]:
# create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# Create empty array with two element
np.empty(2)

array([2.05833592e-312, 2.33419537e-312])

In [5]:
# create an array with range of element
np.arange(4)

array([0, 1, 2, 3])

In [7]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.ones(2, dtype=np.int32)

array([1, 1], dtype=int32)