In [1]:
import numpy as np
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# empty array with two element
np.empty(2)

array([2.05833592e-312, 2.33419537e-312])