# Welcome to `numpy`

# Create basic array

`empty array`

In [1]:
import numpy as np
a = np.empty((3, 4))
print(a)

[[-1.49166815e-154  4.34229915e-311  2.23606798e+000  4.70372193e+000]
 [ 2.73861279e+000  2.23606798e+000  4.70372193e+000  2.73861279e+000]
 [ 2.23606798e+000  2.18434336e-314 -1.73060446e-077  8.38744996e-309]]


`full array`

In [2]:
a1 = np.full((3,4),5)
print(a1)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [2]:
# create an array
import numpy as np
x = np.array([1,2,3,4])
print(x)
print([1,2,3,4] in x.tolist())

[1 2 3 4]
False


In [3]:
# create an array of 10 zeros
a2 =np.zeros(10)
print(a2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# create an array of 10 ones
a3 = np.ones(10)
print(a3)
print(type(a3))


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [6]:
# Create empty array with two element
a4 = np.empty(2)
print(a4)

[2.05833592e-312 2.33419537e-312]


In [3]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [7]:
# create an array with range of element
a5 =np.arange(4)
print(a5)

[0 1 2 3]


In [8]:
a6 =np.arange(2,9,2)
print(a6)

[2 4 6 8]


In [9]:
a7 =np.arange(1,10,2)
print(a7)

[1 3 5 7 9]


In [11]:
a8 =np.linspace(0, 10, num=5)
print(a8)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
a9 = np.ones(2, dtype=np.int32)
print(a9)

[1 1]


In [13]:
a10 = np.zeros((3,4))
print(a10)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Printing 1d, 2d, 3d array

# 1D Array

In [19]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


# 2D Array

In [24]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 3D Array

In [29]:
b = np.arange(12).reshape(3,1,4)
print(b)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [30]:
c = np.arange(24).reshape(3, 2, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


# Find the number of occurrences of a sequence in a NumPy array

In [1]:
import numpy 
arr = numpy.array([[2, 8, 9, 4],  
                   [9, 4, 9, 4], 
                   [4, 5, 9, 7], 
                   [2, 9, 4, 3]]) 
output = repr(arr).count("9, 4") 
print(output)

4


# Find the most frequent value in a NumPy array

In [2]:
import numpy as np 


# create array 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print("Original array:") 
print(x) 

print("Most frequent value in the above array:") 
print(np.bincount(x).argmax())


Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1
