# Basic Operation

In [1]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
x = a - b
print(x)

[10 19 28 37]


In [2]:
c = a + b
print(c)

[10 21 32 43]


In [3]:
d = a * b
print(d)

[  0  20  60 120]


In [5]:
e = a // b
print(e)

[ 0 20 15 13]


/var/folders/qb/t9nvdqln543b469bd7xzrx340000gp/T/ipykernel_1079/3918306879.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  e = a // b


In [6]:
b**2

array([0, 1, 4, 9])

In [7]:
a < 35

array([ True,  True,  True, False])

In [8]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [9]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
A @ B

array([[5, 4],
       [3, 4]])

In [10]:
A .dot(B)

array([[5, 4],
       [3, 4]])

# Adding, removing, and sorting elements

In [13]:
x = np.array([9,4,6,2,3,1,8])
y = np.sort(x)
print(y)
print(type(y))

[1 2 3 4 6 8 9]
<class 'numpy.ndarray'>


In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
x = np.array([[1, 2],[3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
import numpy as np
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_example.ndim

3

In [3]:
array_example.size

24

In [4]:
array_example.shape

(3, 2, 4)

In [5]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [6]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [8]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])