# Basic Operation

In [1]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
x = a - b
print(x)

[10 19 28 37]


In [2]:
c = a + b
print(c)

[10 21 32 43]


In [3]:
d = a * b
print(d)

[  0  20  60 120]


In [5]:
e = a // b
print(e)

[ 0 20 15 13]


/var/folders/qb/t9nvdqln543b469bd7xzrx340000gp/T/ipykernel_1079/3918306879.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  e = a // b


In [6]:
b**2

array([0, 1, 4, 9])

In [7]:
a < 35

array([ True,  True,  True, False])

In [8]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [9]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
A @ B

array([[5, 4],
       [3, 4]])

In [10]:
A .dot(B)

array([[5, 4],
       [3, 4]])