In [1]:
import numpy as np

In [2]:
a = np.array([[1.0, 2.0],[3.0,4.0]])

In [4]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [6]:
b =np.eye(2)   # eye used to create identity matrix
b

array([[1., 0.],
       [0., 1.]])

In [7]:
a * b

array([[1., 0.],
       [0., 4.]])

In [8]:
np.trace(a)

5.0