# splitting arrays

In [1]:
import numpy as np

In [2]:
a = np.floor(10*np.random.random((2, 12)))

In [3]:
a

array([[3., 0., 0., 1., 9., 8., 0., 3., 2., 0., 9., 0.],
       [1., 8., 7., 0., 6., 4., 4., 6., 4., 5., 0., 2.]])

In [4]:
a.shape

(2, 12)

In [5]:
np.hsplit(a,3)

[array([[3., 0., 0., 1.],
        [1., 8., 7., 0.]]),
 array([[9., 8., 0., 3.],
        [6., 4., 4., 6.]]),
 array([[2., 0., 9., 0.],
        [4., 5., 0., 2.]])]

In [8]:
np.hstack(a)   # to concatenate along axis

array([3., 0., 0., 1., 9., 8., 0., 3., 2., 0., 9., 0., 1., 8., 7., 0., 6.,
       4., 4., 6., 4., 5., 0., 2.])

In [9]:
np.hsplit(a,(3,4))

[array([[3., 0., 0.],
        [1., 8., 7.]]),
 array([[1.],
        [0.]]),
 array([[9., 8., 0., 3., 2., 0., 9., 0.],
        [6., 4., 4., 6., 4., 5., 0., 2.]])]