# stacking arrays

In [1]:
import numpy as np

In [2]:
a = np.floor(10*np.random.random((3,3)))
b = np.floor(10*np.random.random((3,3)))

In [6]:
a

array([[9., 0., 5.],
       [2., 0., 1.],
       [6., 4., 9.]])

In [7]:
b

array([[9., 1., 2.],
       [0., 1., 6.],
       [7., 2., 1.]])

In [4]:
np.vstack((a,b))   # concatenate vertically

array([[9., 0., 5.],
       [2., 0., 1.],
       [6., 4., 9.],
       [9., 1., 2.],
       [0., 1., 6.],
       [7., 2., 1.]])

In [5]:
np.hstack((a,b))  # concatenate horizontally

array([[9., 0., 5., 9., 1., 2.],
       [2., 0., 1., 0., 1., 6.],
       [6., 4., 9., 7., 2., 1.]])